name: Publish Docker image
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cartographer_ros
        uses: actions/checkout@v2.3.4
        with:
          repository:  kamilmachon/cartographer_ros
          path: /cartographer_ros
      - name: Checkout cartographer
        uses: actions/checkout@v2.3.4
        with:
          repository:  kamilmachon/cartographer
          path: /cartographer
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          dockerfile: cartographer_ros/Dockerfile
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: kamilmachonhsrn/test
          tag_with_ref: true


