name: Publish Docker image
on:
  workflow_dispatch:
    inputs:
      target_branch_cartographer:
        description: 'branch that will be built on the image'
        required: true
        default: 'master'
      target_branch_cartographer_ros:
        description: 'branch that will be built on the image'
        required: true
        default: 'master'
      cartographer_tag:
        description: 'cartographer image tag'     
        required: true
        default: 'latest'
      output_tag:
        description: 'robo_cart image tag'
        required: true
        default: 'latest'
  repository_dispatch:
    types: [trigger_robo_cart_build]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cartographer_ros
        uses: actions/checkout@v2
        with:
          repository:  kamilmachon/cartographer_ros
          path: cartographer_ros/
          ref: ${{ github.event.inputs.target_branch_cartographer_ros }}
      - name: Checkout cartographer
        uses: actions/checkout@v2
        with:
          repository:  kamilmachon/cartographer
          path: cartographer/
          ref: ${{ github.event.inputs.target_branch_cartographer }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kamilmachonhsrn/test:${{ github.event.inputs.output_tag }}
          context: /home/runner/work/cartographer_ros/cartographer_ros/
          file: cartographer_ros/Dockerfile
          build-args: |
                      INPUT_IMAGE_TAG=${{ github.event.inputs.cartographer_tag }}  

#       - name: Build container image
#         uses: docker/build-push-action@v2
#         with:
#           dockerfile: cartographer_ros/Dockerfile
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#           registry: docker.pkg.github.com
#           repository: ${{ github.repository }}/octo-image
#           tag_with_sha: true
#           tag_with_ref: true
#         - name: Push to Docker Hub
#           uses: docker/build-push-action@v1
#           with:
#             dockerfile: cartographer_ros/Dockerfile
#             username: ${{ secrets.DOCKERHUB_ID }}
#             password: ${{ secrets.DOCKERHUB_PASSWORD }}
#             repository: kamilmachonhsrn/test2
#             tag_with_ref: true




